# Generated by Django 4.2.3 on 2023-07-31 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_record_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('id',)},
        ),
    ]
